#!/bin/bash

#SBATCH -J ParFor2
#SBATCH -n 64           #Number of cores needed
#SBATCH -p holyseasgpu #Partition to submit to
#SBATCH -o OUTPUT2.lsf  #Output file
#SBATCH -t 1000  #Runtime in minutes
#SBATCH --mail-user=samuelkim@college.harvard.edu
#SBATCH --mail-type=END  # The run ended
#SBATCH --mem 10000

mpiexec -n 64 python driver_benchmark.py 1024 4
