#!/bin/bash

#SBATCH -J ParFor
#SBATCH -n 64           #Number of cores needed
#SBATCH -p holyseasgpu #Partition to submit to
#SBATCH -o OUTPUT1.lsf  #Output file
#SBATCH -t 1000  #Runtime in minutes
#SBATCH --mail-user=samuelkim@college.harvard.edu
#SBATCH --mail-type=END  # The run ended

mpiexec -n 64 python driver_benchmark.py 1024 2
mpiexec -n 64 python driver_benchmark.py 1024 4
mpiexec -n 64 python driver_benchmark.py 1024 18
mpiexec -n 64 python driver_benchmark.py 1024 16
mpiexec -n 4 python driver_benchmark.py 1024 4
mpiexec -n 8 python driver_benchmark.py 1024 4
mpiexec -n 16 python driver_benchmark.py 1024 4
mpiexec -n 32 python driver_benchmark.py 1024 4
