#!/bin/bash

#SBATCH -J ParFor32Range
#SBATCH -n 32           #Number of cores needed
#SBATCH -p holyseasgpu #Partition to submit to
#SBATCH -o OUTPUT32range.lsf  #Output file
#SBATCH -t 1000  #Runtime in minutes
#SBATCH --mail-user=samuelkim@college.harvard.edu
#SBATCH --mail-type=END  # The run ended
#SBATCH --mem 10000

mpiexec -n 32 python driver_benchmark_range.py
